# Generated by Django 3.2.5 on 2021-08-04 00:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('add1', models.CharField(max_length=50)),
                ('add2', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('add1', models.CharField(max_length=50)),
                ('add2', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('ssn', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('withholding', models.IntegerField()),
                ('salary', models.CharField(max_length=25)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=25)),
                ('quant', models.IntegerField()),
                ('costper', models.DecimalField(decimal_places=4, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('part_ids', models.CharField(max_length=25)),
                ('part_quants', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('bizname', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('part', models.CharField(max_length=25)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fname', models.CharField(blank=True, max_length=25, null=True)),
                ('lname', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('add1', models.CharField(blank=True, max_length=50, null=True)),
                ('add2', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='po',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=25)),
                ('quant', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(blank=True, null=True)),
                ('ven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_witheld', models.DecimalField(decimal_places=2, max_digits=8)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoice_num', models.AutoField(primary_key=True, serialize=False)),
                ('quant', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(blank=True, null=True)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
    ]
