# Generated by Django 3.2.5 on 2021-08-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='amount_witheld',
            new_name='amount_withheld',
        ),
        migrations.AddField(
            model_name='payroll',
            name='amount_to_match',
            field=models.DecimalField(decimal_places=2, default=55, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
