# Generated by Django 3.2.5 on 2021-07-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='add1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='add2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='ssn',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='employees',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='withholding',
            field=models.IntegerField(),
        ),
    ]
