# Generated by Django 3.2.5 on 2021-08-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210803_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='amount_withheld',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='payroll',
            name='fed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='med',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='sal_after_tax',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='ss',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
