# Generated by Django 3.2.5 on 2021-07-31 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(9999999999)]),
        ),
    ]
