# Generated by Django 3.2.5 on 2021-08-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210803_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='balancesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
