# Generated by Django 3.2.5 on 2021-07-31 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bizname', models.CharField(max_length=25)),
                ('part', models.CharField(max_length=25)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fname', models.CharField(blank=True, max_length=25, null=True)),
                ('lname', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('add1', models.CharField(blank=True, max_length=50, null=True)),
                ('add2', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
