# Generated by Django 3.2.5 on 2021-08-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_product_part_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='threshold',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
