# Generated by Django 3.2.5 on 2021-08-01 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_vendor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.IntegerField()),
                ('part', models.CharField(max_length=25)),
                ('quant', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
