# Generated by Django 3.2.5 on 2021-08-02 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_invoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='po',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=25)),
                ('quant', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(blank=True, null=True)),
                ('ven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendor')),
            ],
        ),
    ]
