# Generated by Django 3.2.5 on 2021-08-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_po_ven'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=25)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quant', models.IntegerField()),
                ('threshold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('part_ids', models.CharField(max_length=25)),
                ('part_quants', models.IntegerField()),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
    ]
