# Generated by Django 3.2.5 on 2021-08-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_inventory_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='part',
            new_name='prod',
        ),
    ]
