# Generated by Django 3.2.5 on 2021-08-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210802_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_quants',
            field=models.CharField(max_length=25),
        ),
    ]
