# Generated by Django 3.2.5 on 2021-08-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_product_part_quants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer',
            new_name='cust',
        ),
    ]
