# Generated by Django 3.2.5 on 2021-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_customer_invoice_cust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_num',
            field=models.AutoField(default=1111, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
