# Generated by Django 3.2.5 on 2021-08-03 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210803_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
    ]
