# Generated by Django 3.2.5 on 2021-08-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_invoice_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
    ]
