# Generated by Django 3.2.5 on 2021-08-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_invoice_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
    ]
