# Generated by Django 3.2.5 on 2021-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_invoice_prod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
